# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: BIGPUMP SmartDefi
email: email@domain.com
author: BIGPUMP SmartDefi
description:  > # "BIGPUMP SmartDefi. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2022 Bigpump. All Rights Reserved.'


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://t.me/bigpump_sd
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: telegram
    url: 
  - title: facebook
    url: 
  - title: comment
    url: 
